fragment ImageThumbnailFragment on FileFieldInterface {
	alt
	basename
	format
	height
	id
	mimeType
	size
	title
	url
	width
	responsiveImage(imgixParams: { w: 800, q: 80, auto: format, ar: "4:3", fit: crop }) {
		alt
		aspectRatio
		base64
		bgColor
		height
		sizes
		src
		srcSet
		webpSrcSet
		title
		width
	}
}
