query AllAbouts($first: IntType = 100, $skip: IntType = 0) {
	allAbouts(first: $first, skip: $skip) {
		...AboutFragment
	}
	_allAboutsMeta {
		count
	}
}

query About($slug: String!) {
	about(filter: { slug: { eq: $slug } }) {
		...AboutFragment
	}
}

fragment AboutFragment on AboutRecord {
	id
	title
	content {
		blocks {
			__typename
			... on ImageRecord {
				id
				image {
					...ImageFragment
				}
			}
			... on ButtonRecord {
				id
				text
				url
			}
		}
		links
		value
	}
	intro {
		blocks
		links
		value
	}
	slug
}
