query AllCourses($first: IntType = 100, $skip: IntType = 0) {
	allCourses(first: $first, skip: $skip, orderBy: [_firstPublishedAt_DESC]) {
		...CourseLightFragment
	}
	_allCoursesMeta {
		count
	}
}
query AllCoursesByWorkshop($workShopId: ItemId!, $first: IntType = 100, $skip: IntType = 0) {
	allCourses(
		first: $first
		skip: $skip
		orderBy: [_firstPublishedAt_DESC]
		filter: { workshop: { eq: $workShopId } }
	) {
		...CourseFragment
	}
	_allCoursesMeta(filter: { workshop: { eq: $workShopId } }) {
		count
	}
}

query Course($slug: String) {
	course(filter: { slug: { eq: $slug } }) {
		...CourseFragment
	}
}

query CourseById($id: ItemId) {
	course(filter: { id: { eq: $id } }) {
		...CourseFragment
	}
}

fragment CourseFragment on CourseRecord {
	id
	title
	date
	intro
	text
	workshop {
		...WorkshopLightFragment
	}
	openToAll
	slug
	_status
}

fragment CourseLightFragment on CourseRecord {
	id
	title
	date
	intro
	text
	workshop {
		...WorkshopLightFragment
	}
	openToAll
	slug
}
