query KnowledgeBaseStart {
	knowledgebaseStart {
		intro {
			blocks
			links
			value
		}
	}
}

query AllKnowledgeBases($first: IntType = 100, $skip: IntType = 0) {
	allKnowledgeBases(first: $first, skip: $skip) {
		...KnowledgeBaseLightFragment
	}
	_allKnowledgeBasesMeta {
		count
	}
}

query KnowledgeBase($slug: String!) {
	knowledgeBase(filter: { slug: { eq: $slug } }) {
		...KnowledgeBaseFragment
	}
}

fragment KnowledgeBaseFragment on KnowledgeBaseRecord {
	id
	title
	intro {
		blocks
		links
		value
	}
	content {
		blocks {
			__typename
			... on VideoExternalRecord {
				id
				video {
					provider
					providerUid
					height
					width
					url
					thumbnailUrl
				}
			}
		}
		links
		value
	}
	image {
		...ImageFragment
	}
	slug
}

fragment KnowledgeBaseLightFragment on KnowledgeBaseRecord {
	id
	title
	intro {
		blocks
		links
		value
	}

	image {
		...ImageThumbnailFragment
	}
	slug
}
