query KnowledgeBaseStart {
	knowledgebaseStart {
		intro {
			blocks
			links
			value
		}
	}
}

query AllKnowledgeBases($first: IntType = 100, $skip: IntType = 0) {
	allKnowledgeBases(first: $first, skip: $skip) {
		...KnowledgeBaseLightFragment
	}
	_allKnowledgeBasesMeta {
		count
	}
}

query KnowledgeBase($slug: String!) {
	knowledgeBase(filter: { slug: { eq: $slug } }) {
		...KnowledgeBaseFragment
	}
}

fragment KnowledgeBaseFragment on KnowledgeBaseRecord {
	id
	title
	content {
		blocks
		links
		value
	}
	image {
		...ImageFragment
	}
	slug
}

fragment KnowledgeBaseLightFragment on KnowledgeBaseRecord {
	id
	title
	content {
		blocks
		links
		value
	}
	image {
		...ImageThumbnailFragment
	}
	slug
}
